export const CHARACTERS_LIST_SUCCESS = 'CHARACTERS_LIST_SUCCESS';
export const CHARACTERS_LIST_IN_PROGRESS = 'CHARACTERS_LIST_IN_PROGRESS';
export const CHARACTERS_LIST_FAILED = 'CHARACTERS_LIST_FAILED';

export const CHARACTER_GET_SUCCESS = 'CHARACTER_GET_SUCCESS';
export const CHARACTER_GET_IN_PROGRESS = 'CHARACTER_GET_IN_PROGRESS';
export const CHARACTER_GET_FAILED = 'CHARACTER_GET_FAILED';

export const EPISODES_LIST_SUCCESS = 'EPISODES_LIST_SUCCESS';
export const EPISODES_LIST_IN_PROGRESS = 'EPISODES_LIST_IN_PROGRESS';
export const EPISODES_LIST_FAILED = 'EPISODES_LIST_FAILED';
